# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='map_item',
            fields=[
                ('map_item_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('map_item_name', models.CharField(max_length=50)),
                ('map_item_address', models.CharField(max_length=256)),
                ('map_item_phone', models.CharField(max_length=50)),
                ('map_item_industry_type', models.CharField(max_length=256)),
                ('map_item_department', models.CharField(max_length=256)),
                ('map_item_email', models.CharField(max_length=256)),
            ],
        ),
    ]
