# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_city_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map_item',
            name='map_item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
